### ISSUE TITLE
Contain all the files into one.

### ISSUE THREAD

**Issue by 3kh0** [EmberNetwork/Blaze#4]
For the index.html file, there are so many links and unneeded files. Making the css and js inline can make it better to develop and understand code.

**Comment by Russell2259** [comment]
Ok, it does pull some assets from https://embernetwork.github.io

**Comment by 3kh0** [comment]
Yeah, just keep it all in one, no need to have it go all over the place

**Comment by Russell2259** [comment]
I'll do that
